title: "Event"
tagline: "Event package for your app and/or domain."
description: "General purpose (DDD friendly) event dispatcher/emitter package."
google_analytics_tracking_id:
versions:
        - '2.0'
        - '1.0'
