title: "Event"
tagline: "Event package for your app and/or domain."
description: "General purpose (DDD friendly) event dispatcher/emitter package."
google_analytics_tracking_id:
versions:
        - name: '3.0 (unreleased)'
          number: '3.0'
        - name: '2.0'
          numer: '2.0'
        - name: '1.0'
          numer: '1.0'
